---
abstract: 'Schema data plugin with default theme for application Commons vote.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Schema-Data-Commons-Vote-Plugin-DefaultTheme
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Activity::Commons::Vote::Load: 0
  Backend::DB::Commons::Vote: 0
  Error::Pure: 0
  Readonly: 0
  Schema::Data::Plugin: 0
  Unicode::UTF8: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/commons-vote/Schema-Data-Commons-Vote-Plugin-DefaultTheme/issues
  homepage: https://github.com/commons-vote/Schema-Data-Commons-Vote-DefaultTheme
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/commons-vote/Schema-Data-Commons-Vote-DefaultTheme
version: '0.01'
